### ISSUE TITLE
Create Documentation for JSON-Formatter tool

### ISSUE THREAD

**Issue by jakenorbie12** [cse210-fa24-group4/cse210-fa24-group4#110]
**Description**
We need to create a docs folder in the admin directory, that will contain a general tutorial for each feature and how to navigate about our app.

**Steps to finish**

1. Create tutorial doc for each feature, including how to use and navigate it.

**Additional Context**
N/A

**Comment by TimKraemer1** [comment]
Is there a specific format we should follow?

**Comment by TimKraemer1** [comment]
done.
