### ISSUE TITLE
Flashing buttons on unix converter

### ISSUE THREAD

**Issue by adrianlayer** [cse210-fa24-group4/cse210-fa24-group4#128]
**Describe the bug**
The first time the unix converter is opened, the buttons flash white AND the copy button's copied notification triggers.

**To Reproduce**
Clear, defined steps to reproduce the behavior:

1. Reload the page
2. Click the unix timestamp converter

**Expected behavior**
The buttons should not flash

**Actual behavior**
The buttons flash

**Desktop (please complete the following information):**

- Browser [e.g. chrome, safari] - firefox, pretty sure others were tested as well
- repro'd across multiple browsers and versions.

**Additional context**
I tried:
- deleting the transition on buttons from index.css
- deleting index.css (really surprised this one didn't work)

I'm pretty sure this is an issue with css loading slowly. Not sure how to address that. Additionally, this was not a problem before the big frontend merge. Which makes no sense because nothing changed in the unix folder.

**Comment by TimKraemer1** [comment]
Looks fixed? Too late to change code but could not replicate it on the website.
