### ISSUE TITLE
Fix HTML rendering before JS when selecting tool

### ISSUE THREAD

**Issue by lauratian** [cse210-fa24-group4/cse210-fa24-group4#82]
**Description**
From initial website load, when user selects a tool, the html renders a couple milliseconds before the JS is applied and does not look polished.

**What is the problem this task addresses?**
UI improvements. Without it, the website does not feel finished.

**What steps need to be taken?**
Find a way to delay rendering of the html until JS has been applied

**Comment by TimKraemer1** [comment]
This has been fixed and incorporated into all tools from all working branches into main.
